language: go

go:
  - 1.14.x


before_install:
  - ./travis/before_install.bash

env:
  global:
    - KITTENHOUSE_ADDR=localhost:13338

before_script:
  - ./travis/before_script.bash

script:
  - go test -v