language: go

go:
  - 1.15.2

dist: focal

before_install:
  - ./travis/before_install.bash

env:
  global:
    - KITTENHOUSE_ADDR=localhost:13338
    - GO111MODULE=off

before_script:
  - ./travis/before_script.bash

script:
  - go test -v